const initialState = {
    stunde: [
        {
          key: "1",
          title: "Arbeit",
          content:
            "Arbeit - Ish",
            stundeGaps: [
              {original:"Ich arbeite seit vier Jahren als Grafiker bei der Firma XZ-Media.",translate:"Men 4 yildan beri grafikchi bo`lib XZ-Media firmasida ishlayapman!"},
              {original:"Ich arbeite schon sieben Jahre als Kfz-Mechaniker in einer Autowerkstatt.",translate:"Men allaqachon 7yildan beri Kfz-mexanigi bo`lib mashina zavodida ishlayman!"},
              {original:"Von August 2013 bis Juli 2015 habe ich als Lehrer gearbeitet. ",translate:"2013-yil avgustidan 2015-yil iyuligacha o`qtuvchi bo`lib ishlaganman."},
              {original:"Meine Arbeitszeit ist/geht täglich von 8:00 Uhr bis 16:30 Uhr.",translate:"Mening ish vaqtim kunduzi soat 8:00 dan 16:30 gacha davom etadi!"},
              {original:"Um 13 Uhr haben/machen wir eine halbe Stunde Mittagspause.",translate:"Soat 13:00 da biz bir yarim soat tushki pauzada bo`lamiz!"},
              {original:"Ich esse mit meinen Arbeitskollegen zu Mittag.",translate:"Men birga ishlayotganlarim bilan tushlikni yeyapman."},
              {original:"Ich arbeite acht Stunden pro Tag/40 Stunden pro Woche.",translate:"Men kuniga 8 soat,haftasiga esa 40 soat ishlayman."},
              {original:"Um vier Uhr nachmittags bin ich mit meiner Arbeit fertig. Dann gehe ich nach Hause. Um 17 Uhr habe ich Feierabend. Nach der Arbeit gehe ich oft einkaufen. ",translate:"- Men 16:00 da ish bilan band bo`laman.Keyin esa uyga boraman.Menda soat 17:00da kechki bayram bo`ladi.Ishdan keyin tez harid qilish uchun boraman."},
              {original:"Zweimal pro Woche gehe ich nach der Arbeit ins Fitnessstudio/Fitnesscenter.",translate:"Haftasiga ikki marta ishdan keyin Fittnes klubga boraman."},
              {original:"Nach der Arbeit gehe ich zum/in den Sprachkurs.",translate:"Men ishdan keyin til kursiga boraman."},
              {original:"Ich arbeite in der Stadt, aber ich lebe in einem Dorf in der Nähe. Deshalb brauche ich ein Auto. ",translate:"Men shaharda ishlayman, lekin yaqindag qishloqda yashayman. Shu sababli menga mashina kerak."},
              {original:"Ich muss jeden Tag Tag 15 Kilometer mit dem Bus/dem Zug/dem Auto/der S-Bahn zur Arbeit fahren.",translate:"- Men har kuni 15 kilometrni avtobusda/poezda/mashinada/metroda ishga borishim kerak."},
              {original:"Ich fahre mit dem Fahrrad/dem Motorrad/der Straßenbahn/der U-Bahn zur Arbeit.",translate:"Men velosiped bilan/mototsikl bilan/metro bilan/tramvay bilan ishga borayapman"},
              {original:"Ich habe es nicht weit zur Arbeit.",translate:"Mening ish joyim uzoq emas."},
              {original:"Ich wohne in der Nähe von meiner Arbeit. Deshalb kann ich zu Fuß zur Arbeit/dorthin gehen.",translate:"Men o`zimning ish joyimdan uzoq bo`lmagan joyda yashayman.Shu sababli men ishga/u yoqqa piyoda bora olaman"},
              {original:"Ich gehe/fahre/brauche (nur) eine halbe Stunde zur Arbeit.",translate:"Men yarim soatda ishga borayapman."},
              {original:"Meine Arbeit/Mein Job gefällt mir (nicht).",translate:"Mening ishim menga yoqadi(yoqmaydi)."},
              {original:"Ich mag meine Arbeit/meinen Job (nicht).",translate:"Menga o`zimni ishim yoqadi(yoqmaydi)."},
              {original:"Meine Arbeit/Mein Job ist sehr stressig und ich habe (leider) nicht viel Freizeit.",translate:"Mening ishim juda strogiy va menda (afsuski) bo`sh vaqtim ko`p emas."},
              {original:"Ich habe eine interessante/stressige Arbeit.",translate:"Menda qiziqarli/strogiy ishim bor."},
              {original:"Ich verdiene wenig/zu wenig/schlecht/genug/gut/viel.",translate:"Men kam/juda kam/yomon/yaxshi/yetarli/ko`p pul ishlab topaman."},
              {original:"Ich verdiene ungefähr 1.300 Euro netto.",translate:"Men taxminan 1.300 Euro pul ishlab topaman."},
              {original:"Jetzt bin ich Rentner/Rentnerin, aber früher habe ich als Fotograf/Fotografin gearbeitet.",translate:"Men hozir nafaqaho`rman,lekin avval rasmchi bo`lib ishlaganman."},
              {original:"Ich bin schon sieben Monate arbeitslos.",translate:"Men allaqachon 7oydan beri ishsizman."},
              {original:"Ich bin seit einem Jahr/seit drei Jahren/seit dem Sommer/seit Januar 2016 arbeitslos. ",translate:"Men bir yildan beri/uch yildan beri/yozdan beri/2016-yil yanvardan beri ishsizman."},
              {original:"Ich habe keine Arbeit/keinen Job.",translate:"Meni ishim yo`q."},
              {original:"Ich suche seit einem halben Jahr (eine) Arbeit/einen Job.",translate:"Men yarim yildan beri ish qidirayapman."},
              {original:"Seit einem Monat suche ich eine Arbeitsstelle.",translate:"Men bir oydan beri ish joy qidiryapman."},
              {original:"Vor vier Monaten habe ich einen neuen Job/eine neue Arbeitsstelle gefunden.",translate:"Men 4oy oldin yangi ish joyini topdim."},
              {original:"Ich lerne Deutsch, weil ich es für meine Arbeit brauche.",translate:"Men nemis tilini o`rganayapman,chunki mening ishim uchun kerak bo`layapdi."},
              {original:"Ich möchte in Deutschland/in Österreich/in der Schweiz arbeiten, deshalb lerne ich Deutsch.",translate:"Men Germaniyada/Avstriyada/Shwetsiyada ishlamoqchiman,shu sababli nemis tilini o`rganayapman."},
              {original:"Auf der Arbeit trage ich andere Kleidung/Klamotten als in meiner Freizeit.",translate:"Ishda men boshqa kiyimlarni bo`sh vaqtimda kiyib ko`raman."},
              {original:"Auf der Arbeit trage ich elegante Kleidung/eine Uniform.",translate:"Men ishda chiroyli kiyimni/uniformani kiyaman."},
              {original:"Für die Arbeit muss ich mich elegant kleiden/anziehen.",translate:"Men ishga yaxshi kiyinishim kerak."},
              {original:"Bei der Arbeit trage ich Anzug, Hemd und Krawatte.",translate:"Ishda kostyum,ko`ylak va galstukda bo`laman."},
              {original:"Beim Arbeiten trage ich ein Kleid oder einen Hosenanzug und eine Bluse.",translate:"Ishda ko`ylakda yoki kofta yupkada bo`laman."},
              {original:"Ich bin krank/krankgeschrieben. Deshalb kann ich nicht auf die Arbeit gehen/arbeiten gehen.",translate:"Men kasalman.Shu sabali ishga bora olmayapman."},
              {original:"Nächste Woche kann ich wieder arbeiten gehen.",translate:"Keyingi hafta men yana ishlay olaman."},
                ],
        },
        {
          key: "2",
          title: "Arbeit",
          content:
            "Arbeit - ish!",
            stundeGaps: [
              {original:"Arbeitest du? Arbeitet ihr? Arbeiten Sie?",translate:"Sen ishlaysanmi? Sizlar ishlaysizlarmi? Siz ishlaysizmi?"},
              {original:"Arbeitest oder studierst du? Arbeitet oder studiert ihr? Arbeiten oder studieren Sie?",translate:"Ishlaysanmi yoki o`qiysanmi? Ishlaysizlarmi yoki o`qiysizlarmi? Ishlaysizmi yo o`qiysizmi?"},
              {original:"Arbeitest du oder gehst du noch zur Schule?",translate:"Ishlaysanmi yoki hali ham maktabga borasanmi?"},
              {original:"Arbeiten Sie oder machen Sie eine Ausbildung?",translate:"Ishlaysizmi yoki ausbildung (o`qiysizmi?) qilasizmi?"},
              {original:"Wo arbeitest du/arbeitet ihr/arbeiten Sie?",translate:"Qayerda ishlaysan / ishlaysizlar / ishlaysiz?"},
              {original:"Seit wann arbeitest du in München? Seit wann arbeiten Sie bei dieser Firma?",translate:"Qachondan  beri Muyunxenda ishlaysan? Qachondan beri bu firmada ishlaysiz?"},
              {original:"Seit wann arbeitest du als Kellner?",translate:"Qachondan beri ofitsant bo`lib ishlaysan?"},
              {original:"Wie sind deine/eure/Ihre Arbeitszeiten?",translate:"Qanday sening / sizlarning / sizning ish vaqtingiz?"},
              {original:"Wann fängt deine/eure/Ihre Arbeit an?",translate:"Qachon sening / sizlarning / sizning ishlaringiz boshlanadi?"},
              {original:"Wann beendest du deine Arbeit? Wann beenden Sie Ihre Arbeit?",translate:"Qachon ishingni tugatasan? Qachon ishingizni tugatasiz?"},
              {original:"Wann bist du/seid ihr/sind Sie mit der Arbeit/mit Arbeiten fertig?",translate:"Qachon (sen) siz ish bilan band bo`lasiz?"},
              {original:"Wann hast du/habt ihr/haben Sie Feierabend?",translate:"Qachon senda / sizlarda / sizda kechki bayram bor?"},
              {original:"Wie viele Stunden arbeitest du/arbeiten Sie pro Tag/Woche?",translate:"Necha soat kuniga ishlayapsiz (ishlayapsan)?"},
              {original:"Was machst du/macht ihr/machen Sie nach der Arbeit?",translate:"Ishdan keyin nima qilayapsan (qilayapsizlar ,qilayapsiz)?"},
              {original:"Hast du viel/genug Freizeit?",translate:"Senda ko`p / yetarlicha bo`sh vaqt bormi?"},
              {original:"Hast du es weit (bis) zur Arbeit?",translate:"Senga ishgacha uzoqmi?"},
              {original:"Wie kommst du/kommt ihr/kommen Sie zur Arbeit?",translate:"Ishga qanday borayapsan (borayapsizlar , borayapsiz)?"},
              {original:"Kannst du/Könnt ihr/Können Sie zu Fuß zur Arbeit gehen?",translate:"Sen (sizlar ,siz) ishga piyoda bora olasanmi (olasizlarmi , olasizmi)?"},
              {original:"Fährst du/Fahrt ihr/Fahren Sie mit dem Auto zur Arbeit?",translate:"Sen (sizlar ,siz) ishga mashina bilan borasanmi (borasizlarmi ,borasizmi)?"},
              {original:"Wie lange fährst du/brauchst du (bis) zur Arbeit?",translate:"Qanchalik uzoq ish joyigacha?"},
              {original:"Wie findest du deine Arbeit/deinen Job? Wie findet ihr eure Arbeit/euren Job?",translate:"Ish joyini qanday topding (topdingiz)?"},
              {original:"Gefällt dir deine Arbeit/dein Job?",translate:"Senga ish joying yoqadima?"},
              {original:"Gefällt euch eure Arbeit/euer Job?",translate:"Sizlarga ish joylaringiz yoqadima?"},
              {original:"Gefällt Ihnen Ihre Arbeit/Ihr Job?",translate:"Sizga ish joyingiz yoqadima?"},
              {original:"Verdienst du/Verdient ihr genug? Verdienen Sie gut?",translate:"Sen (siz) yetarlicha pul ishlaysanmi (ishlaysizlarmi)?"},
              {original:"Wie viel (Geld) verdienst du?",translate:"Qancha pul topasan?"},
              {original:"Seit wann bist du/seid ihr/sind Sie (schon) arbeitslos?",translate:" - Qachondan beri ishsizsan (ishsizsizlar , ishsizsiz)?"},
              {original:"Warum suchst du/sucht ihr/suchen Sie eine neue Arbeit?",translate:"Nima uchun sen (sizlar , siz) yangi ish joyini qidirayapsan (qidirayapsizlar , qidirayapsiz)?"},
              {original:"Seit wann suchst du/sucht ihr/suchen Sie schon einen (neuen) Job/eine Arbeitsstelle?",translate:"Qachondan beri ish joyini qidirayapsan (qidirayapsizlar , qidirayapsiz)?"},
              {original:"Welche Kleidung trägst du/tragt ihr/tragen Sie auf der Arbeit?",translate:"Ishda qanaqa kiyimlarni kiyinasan (kiyinasizlar , kiyinasiz)?"},
              {original:"Was für Klamotten trägst du auf der Arbeit?",translate:"Ishda qanaqa kiyimda bo`lasan?"},
                ],
        },
        

        {
          key: "3",
          title: "Wohnort",
          content:
            "Wo ich wohne und wo ich gewohnt habe.",
            stundeGaps: [
              {original:"Ich lebe/wohne in Berlin/in Deutschland.",translate:"Men Berlinda  / Germaniyada yashayapman."},
              {original:"Ich lebe/wohne in der Türkei/in der Schweiz.",translate:"Men Turkiyada / Shwetsiyada yashayapman."},
              {original:"Ich lebe/wohne im/in Iran.",translate:"Men Iroqda yashayapman."},
              {original:"Ich lebe/wohne in den USA/in den Niederlanden.",translate:"Men Amerikada / Niderlandiyada yashayapman."},
              {original:"Ich lebe/wohne auf Teneriffa/auf Mallorca/auf Korsika/auf einer Insel.",translate:"Men orolda(...) yashayapman."},
              {original:"Ich komme aus Usbekistan, aber ich lebe seit 2015 in Deutschland.",translate:"Men Usbekistandan kelganman, lekin 2015 yildan beri Germaniyada yashayapman."},
              {original:"Ich lebe in einer Stadt/in einem Dorf/auf dem Land.",translate:"Men shaharda / qishloqda yashayapman."},
              {original:"Berlin liegt im Osten von Deutschland.",translate:"Germaniyaning sharqida Berlin joylashgan."},
              {original:"Die Stadt liegt im Norden/im Süden/im Westen/im Osten/im Zentrum von Usbekistan.",translate:"Shahar O`zbekistonning shimolida / Janubida / G`arbida / Sharqida / markazida joylashgan."},
              {original:"Das Dorf liegt in der Nähe von Hamburg.",translate:"Qishloq Hamburgdan uzoq bo`lmagan joyda joylashgan."},
              {original:"Erpel liegt bei Bonn.",translate:"Erpel Bonnda joylashgan."},
              {original:"Mein Dorf liegt/ist etwa 20 Kilometer von Wien entfernt.",translate:"Mening qishlog`im Vena shahridan 20 kilometrlar chamasidagi uzoqlikda joylashgan."},
              {original:"Die Stadt/Das Dorf liegt an einem Fluss.",translate:"Shahar / qishloq daryo bo`yida joylashgan."},
              {original:"Der Ort liegt am Rhein. Die Stadt liegt an der Elbe.",translate:"Bu joy Rayn daryosi bo`yida joylashgan. Shahar Elba daryosi bo`yida joylashgan!"},
              {original:"Ich wohne/lebe schon immer in Berlin. Ich bin hier geboren und aufgewachsen.",translate:"Men har doim Germaniyada yashayman. Men bu yerda tug`ilganman va katta bo`ldim."},
              {original:"Ich wohne/lebe seit dreizehn Jahren im Zentrum/in der Altstadt/am Stadtrand von Zürich.",translate:"Men 13 yildan beri Zurix shahrining markazida / eski shahrida / shahar chetida yashayapman."},
              {original:"Ich lebe seit 2003 mit meinem Freund/meinem Mann in Hamburg.",translate:"Men 2003-yildan beri do`stim bilan / erim bilan Hamburgda yashayapman."},
              {original:"Ich wohne schon lange mit meiner Freundin/meiner Frau/meiner Familie in Dresden.",translate:"Men anchadan beri dugonam bilan / hotinim bilan / oilam bilan Dresdenda yashayapman."},
              {original:"Ich lebe seit zehn Jahren mit meinem Kind in Weimar.",translate:"Men o`n yildan beri farzandim bilan Vaymerda yashayapman."},
              {original:"Ich wohne seit einem Jahr mit meinen Kindern in Leverkusen.",translate:"Men 1 yildan beri farzandim bilan Leverkusenda yashayapman."},
              {original:"Vor drei Jahren bin ich von Bonn nach Berlin gezogen.",translate:"3 yil oldin Bondan Berlinga ko`chib kelgandim."},
              {original:"Mit 16 Jahren bin ich nach Deutschland gekommen/gegangen.",translate:"16 yoshimda Germaniyaga kelganman."},
              {original:"Früher/Vorher habe ich in Madrid/in Marokko/in der Türkei gelebt.",translate:"Avval Madridda / Marokkoda / Turkiyada yashadim."},
              {original:"Vor 5 Jahren bin ich/ist meine Familie von Nürnberg nach München gezogen.",translate:"5 yil oldin mening oilam Nurnbergdan Munxenga ko`chib kelishgan."},
              {original:"Von 2008 bis 2013 habe ich in Konstanz gelebt.",translate:"2018-yildan 2013-yilgacha Konstanda yashagandim."},
              {original:"Ich habe lange (Zeit) in Süddeutschland gelebt.",translate:"Men uzoq vaqt Janubiy Germaniyada yashadim."},
              {original:"Ich lebe/wohne bei meinem Vater/meiner Mutter/meinen Eltern.",translate:"Men otamnikida / onamnikida / ota-onamnikida yashayapman."},
              {original:"Unsere Kinder wohnen/leben nicht mehr bei uns. Sie sind vor ein paar Jahren ausgezogen.",translate:"Bizning farzandlar biznikida yashashmaydilar. Ular ikki yil oldin ko`chib ketishgan!"},
              {original:"Ich wohne/lebe in einer Wohngemeinschaft/WG.",translate:"Men yotoqxonada yashayapman."},
              {original:"Ich wohne mit meiner Familie in einem Haus am Stadtrand.",translate:"Men oilam bilan shahar chetida yashaymiz."},
              {original:"Ich wohne in einer Wohnung im Stadtzentrum.",translate:"Men bir honalik kvartirada shahar markazida yashayman!"},
              {original:"Wir haben eine kleine Wohnung im Zentrum.",translate:"Biz shahar markazida kichkina uyda yashaymiz!"},
              {original:"Mein Stadtteil/Stadtviertel heißt…",translate:"Mening mahallam ataladi ..."},
              {original:"Die Stadt/Das Dorf ist klein/groß/nicht sehr groß.",translate:"Shahar / Qishloq kichkina / katta / katta emas."},
              {original:"Die Stadt hat ungefähr/fast/über eine Million/zwei Millionen Einwohner.",translate:"Shahar taxminan / deyarli / 1 milliondan ortiq / 2 milliondan ortiq aholi bor."},
              {original:"In Freiburg leben etwa 230.000 Menschen/Personen.",translate:"Frayburgda Taxminan 230 000 inson yashaydi."},
              {original:"Die Stadt/Das Dorf ist (schon) sehr alt.",translate:"Shahar / qishloq juda qadimiy."},
              {original:"Ich wohne/lebe (nicht) gern in…",translate:"Men maza qilib yashaya(ma)pman ...da."},
              {original:"Ich lebe (nicht) gern in diesem Stadtteil.",translate:"Men maza qilib bu shahar qismida yashaya(ma)pman."},
              {original:"Die Stadt/Der Stadtteil gefällt mir (nicht).",translate:"Bu shahar/ mahalla menga yoqadi (yoqmaydi)."},
              {original:"Meine Freunde und Familie leben (auch) hier.",translate:"Mening do`stim va oilam bu yerda yashaydi."},
              {original:"Ich habe (nicht) gern in… gelebt.",translate:"Men maza qilib qaysidir shaharda yashay ol(ma)dim."},
              {original:"Ich mag den Stadtteil/die Stadt/das Dorf/die Region.",translate:"Menga mahalla / shahar / qishloq / region yoqadi."},
              {original:"Ich lebe noch nicht so lange/erst drei Monate hier und kenne noch nicht so viele Leute.",translate:"Men unchalik uzoq emas / endi 3 oy bo`ldi yashayotganimga va men hali hamma odamlarni tanimayman."},
              {original:"Ich lebe in…, aber arbeite in… ",translate:"Men qaysidir shaharda yashayman , lekin boshqa qaysidir shaharda ishlayapman."},
              {original:"Deshalb muss ich mit dem Auto/mit dem Bus/mit dem Zug zur Arbeit fahren.",translate:"Shu sababli mashina bilan / avtobus bilan / poyezd bilan ishga bormoqchiman."},
              {original:"Ich möchte/will hier nicht (mehr) leben.",translate:"Men bu yerda ishlamoqchi(mas)man."},
              {original:"Ich möchte/will (für) immer hier leben.",translate:"Men bu yerda yashamoqchiman."},
              {original:"Ich möchte/will in… leben. ",translate:"Men qaysidir shaharda yashamoqchiman."},
              {original:"Ich habe ein Jahr (lang) in Paris gelebt.",translate:"Men parijda 1 yil yashaganman."},
              {original:"Salzburg gefällt mir, weil man dort viel machen kann.",translate:"Salzburg menga yoqadi , chunki u yerda ko`p narsa qila olaman."},
              {original:"Paris ist meine Lieblingsstadt.",translate:"Parij mening sevimli shaharim."},
              {original:"Meine Lieblingsstadt ist Berlin.",translate:"Mening sevimli sharim Berlin."},
              {original:"Ich wohne gern in der/dieser Stadt.",translate:"Men bajonidil bu shaharda yashayapman."},
              {original:"Ich lebe lieber auf dem Land als in der Stadt.",translate:"Men bajonidil shahar sifatidagi qishloqda yashayapman."},
            ]
          },

          {
            key: "4",
            title: "Wohnort",
            content:
              "Was es an meinem Wohnort gibt?",
              stundeGaps: [
                {original:"In… gibt es viele Hotels, Geschäfte, Supermärkte und ein großes Einkaufszentrum.",translate:"Qaysi shahardadir juda ko`p mehmonhonalar / magazinlar / supermarktlar va savdo majmualari bor."},
                {original:"Ich wohne im Zentrum, deshalb gibt es viele Geschäfte in der Nähe.",translate:"Men markazda yashayapman , chunki yaqin orada ko`p magazinlar bor."},
                {original:"In dem Stadtteil gibt es viele Kneipen, Cafés und Restaurants. Es gibt auch ein Kino, einen Park und ein Museum.",translate:"- Bu shaharning qismida ko`plab Kafelar , restaranlar va barlar.Bu yerda kino , park va muzey bor."},
                {original:"Alles ist in der Nähe und ich kann immer zu Fuß gehen.",translate:"Hammasi yaqinda va men har doim piyoda bora olmayman."},
                {original:"Deshalb wohne ich gern im Zentrum.",translate:"Shu sabali men shahar markazida yashayapman."},
                {original:"Leider gibt es in meinem Dorf keinen Supermarkt. Deshalb brauche ich ein Auto. ",translate:"Afsuski mening qishlog`imda Supermarkt yuq.Shu sababli menga mashina kerak."},
                {original:"In… haben wir eine Bäckerei, eine Metzgerei und ein kleines Lebensmittelgeschäft. ",translate:"Qaysidir joyda bizda qassobhona va kichkina savdo magazini."},
                {original:"Außerdem gibt es einen Arzt und eine Apotheke.",translate:"Bundan tashqari 1 ta shifohona va apteka ham bor."},
                {original:"Es gibt (leider) keine Apotheke. Es fehlt eine Apotheke.",translate:"Afsuski u yerda apteka yuq. Dorixona yo'q."},
                {original:"In… gibt es viele Kindergärten und Schulen. Es gibt auch ein Krankenhaus.",translate:"Qaysidir joyda ko`plab bolalar bog`chasi va maktablar bor. Kasalhona ham bor."},
                {original:"Es gibt einen Kindergarten/eine Schule/eine Universität.",translate:"Bolalar bog`chasi , maktab , Universitet bor."},
                {original:"In der Altstadt sieht man viele alte Gebäude, Plätze und Kirchen.",translate:"Eski shaharda ko`plab eskiy binolar , maydonlar va madrasalarni ko`rishyapdilar."},
                {original:"Es gibt auch eine Moschee/eine Synagoge/einen Tempel.",translate:"Bu yerda ham bor masjidlar , ibodatxonalar."},
                {original:"Es gibt viele Hochhäuser.",translate:"Ko`plab osmono`par binolar bor."},
                {original:"Hier kann man sehr viele Sehenswürdigkeiten wie das alte Rathaus und die Kathedrale besichtigen.",translate:"Bu yerda juda ko`plab diqqatga sazovor joylar huddi eski oqsaroylarni kurishadilar."},
                {original:"Es gibt eine Straßenbahn, viele Busse und auch eine U-Bahn. Deshalb brauche ich kein Auto.",translate:"Metrolar , ko`plab avtobuslar va trolleybuslar ham bor.Shu sababli menga mashina kerak emas."},
                {original:"Der Bahnhof ist im Zentrum von der Stadt.",translate:"Vokzal shahar markazida joylashgan."},
                {original:"Die Stadt hat einen Flughafen.",translate:"Shaharda aeroport bor."},
                {original:"Bonn ist die perfekte Stadt für mich.",translate:"Bon men uchun alo darajadagi shahar."},
                {original:"Für mich ist Freiburg die perfekte Stadt.",translate:"Menga Frayburg alo darajadagi shahar."},
                {original:"Was man an meinem Wohnort machen kann. ",translate:"Mening tug`ilgan joyimda nima qilsa bo`ladi?"},
                {original:"In meiner Stadt/meinem Dorf kann man sehr viel/nicht viel machen. ",translate:"Mening shaharimda / qishlog`imda juda ko`plab narsa qilsa bo`ladi (bo`lmaydi)."},
                {original:"Im Stadtzentrum gibt es viele Geschäfte. Dort kann man gut einkaufen gehen. Ich gehe dort oft mit meinen Freunden/meinen Freundinnen einkaufen/shoppen.",translate:"Shahar markazida ko`plab magazinlar bor.U yerga yaxshi savdo qilishga borsa bo`ladi.Men tez-tez u yoqqa boraman do`stlarim bilan."},
                {original:"Ich gehe dort oft mit meinen Freunden/meinen Freundinnen einkaufen/shoppen.",translate:"- Shahar markazida ko`plab magazinlar bor.U yerga yaxshi savdo qilishga borsa bo`ladi.Men tez-tez u yoqqa boraman do`stlarim bilan."},
                {original:"Ich fahre oft ins Stadtzentrum und gehe dort spazieren.",translate:"Men tez-tez shahar markaziga borayapman va u yerga sayohat qilishga boraman."},
                {original:"Auf dem Marktplatz gibt es dreimal pro Woche einen Markt. Dort kann man immer frische Produkte kaufen.",translate:"Bozor maydonida haftasiga 3 marta bozor bo`lib o`tadi.U yerda yangi mahsulotlarni sotib olishadilar."},
                {original:"Auf dem Markt kaufe ich oft frisches Obst und Gemüse.",translate:"Bozorda men tez-tez yangi sabzavotlarni va mevalarni sotib olayapman."},
                {original:"Das Freizeitangebot ist (sehr) groß und gut.",translate:"Dam olish taklifi juda yaxshi va katta."},
                {original:"Man kann Sport treiben, mit Freunden ins Kino oder (ins) Theater gehen und mit der Familie im Park spazieren gehen.",translate:"Sport bilan shug`urlanish , do`stlar bilan kinoga yoki teatrga borish va oila bilan parkda sayohat qilish mumkun."},
                {original:"Ich gehe oft in den Park, um dort mit Freunden Volleyball oder Fußball zu spielen. ",translate:"Men tez-tez parkka boraman , u yerda futbol yoki valeybol o`ynash uchun."},
                {original:"Es gibt viele Spielplätze. Dort können die Kinder spielen.",translate:"Ko`plab o`yin maydonlari bor. U yerda bolalar o`ynay oladilar."},
                {original:"Außerdem gibt es ein Schwimmbad. Im Sommer gehe ich mit meinen Freunden/meinen Freundinnen ins Schwimmbad.",translate:"Bundan tashqari suzish havzasi bor. Yozda men do`stlarim bilan suzish havzasiga boraman."},
                {original:"Die Stadt liegt am Meer und es gibt einen Strand. Ich gehe oft an den Strand.",translate:"Shahar dengiz bo`yida joylashgan va playaji ham bor.Men tez-tez plyajga borayapman."},
                {original:"Ich mache gern Sport und trainiere dreimal pro Woche im Fitnessstudio.",translate:"Men sport bilan bajonidil shug`urlanaman va haftasiga 3 marta fitnes klubda shug`urlanaman."},
                {original:"Es gibt oft gute Konzerte.",translate:"Tez-tez yaxshi konsertlar bo`ladi."},
                {original:"Im Museum gibt es oft interessante Ausstellungen.",translate:"Muzeyda tez-tez qiziqarli ko`rgazmalar bo`ladi."},
                {original:"Ich gehe oft ins Museum.",translate:"Men tez-tez muzeyga boraman."},
                {original:"In den Kneipen und Cafes kann man Freunde treffen.",translate:"Turli hil barlarda va kafelarda do`stlar uchrashisha olishadilar."},
                {original:"Man kann in… abends gut ausgehen / essen gehen.",translate:"Qaysidir joyda kechalarni yaxshi o`tkazsa bo`ladi."},
                {original:"Es gibt viele Restaurants. Dort kann man gut essen.",translate:"Ko`plab restaranlar bor. U yerda yaxshi ovqatlansa bo`ladi."},
                {original:"Ich wohne gern hier,…",translate:"Men bajonidil bu yerda yashayman , ..."},
                {original:"… weil die Stadt sehr interessant ist.",translate:"... chunki shahar juda chiroyli."},
                {original:"… weil man viel machen kann.",translate:"... chunki ko`p narsa qilsa bo`ladi."},
                {original:"… weil meine Familie hier lebt.",translate:"... chunki mening oilam bu yerda yashaydi."},
                {original:"… weil ich hier gute Freunde habe.",translate:"... chunki bu yerda yaxshi do`stlarim bor."},
                {original:"Ich lebe gern hier, denn die Stadt ist sehr ruhig und gemütlich.",translate:"Men bajonidil bu yerda yashayapman , chunki shahar tinch va juda qulay."},
                {original:"Ich finde die Stadt langweilig. Deshalb will ich nicht mehr hier leben.",translate:"Men shaharni zerikarli hisoblayman. Shu sababli men bu yerda ko`p yashamoqchimasman."},
              ]
            },

            {
              key: "5",
              title: "Wohnort",
              content:
                "Wo ich wohne und wo ich gewohnt habe.",
                stundeGaps: [
                  {original:"Wo wohnst/lebst du? ",translate:"Qayerda yashayapsan?"},
                  {original:"Wo wohnt/lebt ihr?",translate:"Qayerda sizlar yashayapsizlar?"},
                  {original:"Wo wohnen/leben Sie?",translate:"Qayerda siz yashayapsiz?"},
                  {original:"Wohnst du/Wohnt ihr/Wohnen Sie in einem Dorf oder in einer Stadt?",translate:"Yashayapsanmi / yashayapsizlarmi / yashayapsizmi qishloqda yoki shaharda?"},
                  {original:"Wohnst du/Wohnt ihr/Wohnen Sie im Stadtzentrum oder am Stadtrand? ",translate:"Yashayapsanmi / yashayapsizlarmi / yashayapsizmi shahar markazida yoki shahar chetida."},
                  {original:"Wo liegt das Dorf/die Stadt?",translate:"Qishloq / Shahar qayerda joylashgan?"},
                  {original:"Wie viele Einwohner hat die Stadt/das Dorf? ",translate:"Shaharda / qishloqda qancha aholi yashaydi?"},
                  {original:"Seit wann wohnst du in Frankfurt? ",translate:"Sen qachondan beri Frankfurtda yashayapsan?"},
                  {original:"Seit wann wohnt ihr hier? ",translate:"Qachondan beri sizlar bu yerda yashayapsizlar?"},
                  {original:"Seit wann wohnen Sie dort?",translate:"Qachondan beri siz u yerda yashayapsiz?"},
                  {original:"Wie lange lebst du schon im Ausland?",translate:"Qancha vaqt chet elda yashayadingiz?"},
                  {original:"Wie lange lebt ihr schon in Deutschland? ",translate:"Qancha vaqt sizlar Germaniyada yashadingizlar?"},
                  {original:"Wie lange leben Sie schon in Dortmund? ",translate:"Qancha vaqt siz Dortmundda yashadingiz?"},
                  {original:"Lebst du schon immer in Österreich?",translate:"Sen Avstriyada allaqachondan beri yashayapsanmi?"},
                  {original:"Lebt ihr schon immer in Bamberg?",translate:"Sizlar Bambergda allaqachondan beri yashayapsizlarmi?"},
                  {original:"Leben Sie schon immer hier?",translate:"Siz bu yerda allaqachondan beri yashayapsizmi?"},
                  {original:"Wo hast du vorher gewohnt?",translate:"Sen avval qayerda yashagansan?"},
                  {original:"Wo habt ihr früher gewohnt?",translate:"Sizlar avvalllari qayerda yashagansizlar?"},
                  {original:"Wo haben Sie vorher gewohnt?",translate:"Siz avvalllari qayerda yashagansiz?"},
                  {original:"Wie lange hast du dort gelebt?",translate:"Qancha vaqt sen u yerda yashading?"},
                  {original:"Wie lange habt ihr dort gelebt?",translate:"Qancha vaqt sizlar u yerda yashadingizlar?"},
                  {original:"Wie lange haben Sie dort gelebt?",translate:"Qancha vaqt siz u yerda yashadingiz?"},
                  {original:"Mit wem wohnst/lebst du zusammen?",translate:"Sen kim bilan birga yashayapsan?"},
                  {original:"Mit wem wohnt/lebt ihr zusammen?",translate:"Sizlar kim bilan birga yashayapsizlar?"},
                  {original:"Mit wem wohnen/leben Sie zusammen?",translate:"Siz kim bilan birga yashayapsiz?"},
                  {original:"Lebst du noch bei deinen Eltern?",translate:"Sen hali ham ota-onangnikida yashayapsanmi?"},
                  {original:"Lebt ihr noch bei euren Eltern?",translate:"Sizlar hali ham ota-onangnikizlarda yashayapsizlarmi?"},
                  {original:"Leben Sie noch bei Ihren Eltern?",translate:"Siz hali ham ota-onangiznikida yashayapsizmi?"},
                  {original:"Lebst du gern in Bonn?",translate:"Sen Bonda yashashni yoqtirasanmi?"},
                  {original:"Lebt ihr gern in der Stadt?",translate:"Sizlar Bonda yashashni yoqtirasizlarmi?"},
                  {original:"Leben Sie gern auf dem Land?",translate:"Siz Bonda yashashni yoqtirasizmi?"},
                  {original:"Wohnst du/Wohnt ihr lieber in der Stadt oder auf dem Land?",translate:"Sen / siz bajonidil bu shaharda yoki qishloqda yashayapsizlarmi?"},
                  {original:"Wie findest du/findet ihr/finden Sie die Stadt/das Dorf/den Stadtteil?",translate:"Qanday hisoblaysan shaharni / qishloqni / shaharning bir qismini?"},
                  {original:"Gefällt dir/euch/Ihnen Hannover?",translate:"Senga / sizlarga / sizga Hannover yoqadima?"},
                  {original:"Warum/Wieso gefällt dir/euch/Ihnen Innsbruck (nicht)?",translate:"Nima uchun senga / sizlarga / sizga Innsburg yoqadi (yoqmaydi) ?"},
                  {original:"Was/Welche ist deine/eure/Ihre Lieblingsstadt?",translate:"Qaysi shahar sening / sizlarning / sizning sevimli shahringiz?"},
                  {original:"Wo möchtest/willst du (gern) leben?",translate:"Qayerda sen yashamoqchisan?"},
                  {original:"Wo möchtet/wollt ihr (gern) leben?",translate:"Qayerda sizlar yashamoqchisizlar?"},
                  {original:"Wo möchten/wollen Sie (gern) leben?",translate:"Qayerda siz yashamoqchisiz?"},
                ]
              },

              {
                key: "6",
                title: "Wohnort",
                content:
                  "Was es an meinem Wohnort gibt.",
                  stundeGaps: [
                    {original:"Was gibt es in deiner/eurer/Ihrer/der Stadt?",translate:"Sening / sizlarning / sizning shahringizda nima bor?"},
                    {original:"Was gibt es in deinem/eurem/Ihrem/dem Dorf?",translate:"Sening / sizlarning / sizning qishlog`ingizda nima bor?"},
                    {original:"Was gibt es in deinem/eurem/Ihrem/dem Stadtteil?",translate:"Sening / sizlarning / sizning shaharchada nima bor?"},
                    {original:"Was gibt es an deinem/eurem/Ihrem/dem Wohnort?",translate:"Sening / sizlarning / sizning yashayotgan joyda nima bor?"},
                    {original:"Was gibt es in der Nähe von deinem/eurem/Ihrem Haus?",translate:"Sening / sizlarning / sizning uyingiz yaqinida nima bor?"},
                    {original:"Was gibt es in der Nähe von deiner/eurer/Ihrer Wohnung?",translate:"Sening / sizlarning / sizning kvartirangiz yaqinida nima bor?"},
                    {original:"Was fehlt in…? Was gibt es nicht in…?",translate:"Nima yo`q ...da?"},
                    {original:"Gibt es in… einen Kindergarten/eine Grundschule/eine Schule/ein Gymnasium/ eine Universität?",translate:"Bolalar bog`chasi / umumiy maktab / maktab / Gymnaziya / universitet bormi?"},
                    {original:"Ist … eine alte Stadt?",translate:"Eski shaharmi ...?"},
                    {original:"Wie alt ist die Stadt?",translate:"Bu shahar necha yoshda?"},
                    {original:"Ist die Stadt schön/modern/international/alt?",translate:"Shahar chiroylimi / zamonaviymi / halqaromi / qadimiymi?"},
                    {original:"Gibt es eine schöne Altstadt?",translate:"Chiroyli qadimiy shaharlar bormi?"},
                    {original:"Gibt es in… eine Straßenbahn/eine U-Bahn/einen Flughafen?",translate:"...da trolleybus / metro / aeroport bormi?"},
                    {original:"Was man an meinem Wohnort machen kann."},
                    {original:"Was man an meinem Wohnort machen kann.",translate:"Mening yashayotgan joyda nimalar qilsalar bo`ladi."},
                    {original:"Was kann man in… machen?",translate:"... da nimalar qila oladilar?"},
                    {original:"Was machst du gern in…?",translate:"...da sen yoqtirib nima qilayapsan?"},
                    {original:"Was macht ihr gern in…?",translate:"...da sizlar dildan nima qilayapsizlar?"},
                    {original:"Was machen Sie gern in…?",translate:"...da siz bajonidil nima qilayapsiz?"},
                    {original:"Was machst du am Wochenende in…?",translate:"... da hafta oxirida nima qilayapsan?"},
                    {original:"Kann man in… gut einkaufen gehen?",translate:"...da nimalarni xarid qilishga borayaptilar?"},
                    {original:"Kann man in… gut ausgehen/essen gehen?",translate:"...da nimani tanavvur qilishga borayapdilar?"},
                  ]
                },

                {
                  key: "7",
                  title: "Meine Wohnung / Mein Haus",
                  content:
                    "Meine Wohnung / Mein Haus - Mening kvartiram / mening uyim",
                    stundeGaps: [
                      {original:"Ich wohne in einem Haus.",translate:"Men bir uyda yashayapman."},
                      {original:"Ich wohne in einer Wohnung.",translate:"Men bir kvartirada yashayapman."},
                      {original:"Ich wohne mit meiner Familie in einem Haus mit Garten.",translate:"Men ota-onam bilan bir bog`i bor uyda yashayapman."},
                      {original:"Ich wohne in einer kleinen Wohnung in der Stadt.",translate:"Men shaharda kichkina kvartirada yashayman."},
                      {original:"Ich habe ein Appartment im Stadtzentrum gemietet.",translate:"Men shahar markazidagi apparmentni ijaraga olgan edim."},
                      {original:"Wir haben eine 4-Zimmer-Wohnung in einem Wohnblock/in einem Hochhaus.",translate:"Bizda domda to`rt honali kvartiramiz bor."},
                      {original:"Die Wohnung ist im Erdgeschoss/im ersten/zweiten/dritten/vierten/fünften Stock.",translate:"Kvartira birinchi etajda / ikkinchi etajda / uchinchi etajda ..."},
                      {original:"Die Wohnung ist in der ersten/zweiten/dritten/vierten/fünften Etage.",translate:"Kvartira ikkinchi etajda ..."},
                      {original:"Ich wohne mit meinem Freund/meiner Freundin/meiner Familie/meinen Eltern zusammen.",translate:"Men do`stim bilan / dugonam bilan / oilam bilan / ota-onam bilan birga yashayman."},
                      {original:"Wir wohnen schon vier Jahre (lang) zusammen.",translate:"Biz allaqachondan beri 4 yildan beri birga yashaymiz."},
                      {original:"Wir wohnen erst drei Monate zusammen.",translate:"Biz endi uch oydan beri birga yashaymiz."},
                      {original:"Wir wohnen seit einem Jahr zusammen.",translate:"Biz yanvardan beri birga yashayapmiz."},
                      {original:"Wir leben seit 2013 zusammen.",translate:"Biz 2013 yildan beri birga yashaymiz."},
                      {original:"Ich wohne (noch) bei meinen Eltern.",translate:"Men ota-onamnikida yashayaoman."},
                      {original:"Ich wohne/lebe allein.",translate:"Men yolg`iz yashayman."},
                      {original:"Ich wohne seit drei Jahren in einer Wohngemeinschaft (WG).",translate:"Men uch yildan beri yotoqxonada yashayapman."},
                      {original:"Ich habe ein Zimmer in einer WG.",translate:"Menda bir hona bor yotoqxonadan."},
                      {original:"Meine/Unsere Wohnung hat drei Schlafzimmer, ein Badezimmer/ein Bad, eine Toilette/ein Klo, eine Küche, ein Wohnzimmer und einen kleinen Balkon.",translate:"Mening kvartiramda uchta dam olish xonasi , yuvinish xonasi , hojatxona , oshxona , hordiq xonasi va kichkina balkoni bor"},
                      {original:"Die Kinder schlafen und spielen im Kinderzimmer.",translate:"Bolalar uhlashayapdilar va bolalar xonasida o`ynashayapdilar."},
                      {original:"Wir essen in der Küche/im Esszimmer.",translate:"Biz oshxonada ovqatlanayapmiz."},
                      {original:"Meine/Unsere Wohnung hat ein Arbeitszimmer mit einem Bücherregal und einem Schreibtisch. Dort ist/steht auch mein Computer und der Drucker.",translate:"Mening kvartiramda kitob javoni va yozuv stoli bilan ishxonasi bor.U yerda mening kompyuterim va printer turadi."},
                      {original:"In der Küche gibt es einen Tisch mit Stühlen, einen Küchenschrank, einen Kühlschrank, einen Herd und einen Backofen.",translate:"Oshxonada stol sullari bilan , muzlatgich , pishiriqlar uchun gaz, gaz va makrovelka bor."},
                      {original:"Im Wohnzimmer steht ein Wohnzimmerschrank. Dort sind auch zwei Sessel, ein Sofa und ein Tisch.",translate:"Dam olish xonasida shkaf bor. U yerda ikkita kreslo, divan va stol ham bor."},
                      {original:"Im Schlafzimmer sind zwei Betten, zwei Nachttische und ein Kleiderschrank.",translate:"Dam olish xonasida ikkita kravat , ikkita tungi stol va kiyim javoni bor."},
                      {original:"Im Badezimmer gibt es eine Dusche, eine Badewanne, ein Klo, ein Waschbecken und einen Spiegel.",translate:"Yuvinish xonasida dush , hojatxona , umivalnik va oyna bor."},
                      {original:"Ich wohne erst ein Jahr in der Wohnung.",translate:"Men endi honada birinchi yil yashashim."},
                      {original:"Ich wohne schon 26 Jahre in dem Haus.",translate:"Men 26 yildan beri hovlida yashayapman."},
                      {original:"Wir wohnen seit 3 Jahren dort.",translate:"Biz uch yildan beri u yerda yashayapmiz."},
                      {original:"Vorher/Früher habe ich/haben wir in einer Wohnung in der Stadt gewohnt.",translate:"Avvallari men / biz shaharda kvartirada yashaganman."},
                      {original:"Wir wohnen in einem Vorort von Bonn.",translate:"Biz Bonning atrofida yashayapmiz."},
                      {original:"Wir wohnen (jetzt) auf dem Land.",translate:"Biz qishloqda yashayapmiz."},
                      {original:"Ich wohne lieber in der Stadt als auf dem Land.",translate:"Men shaharda huddi qishloqdagidek sevib yashayman."},
                      {original:"Ich wohne lieber in einem Dorf als in einer Stadt.",translate:"Men qishloqda huddi shahardagidek maza qilib yashayapman."},
                      {original:"Die Wohnung gefällt mir/uns.",translate:"Kvartira menga / bizga yoqadi."},
                      {original:"Mir/Uns gefällt meine/unsere Wohnung.",translate:"Menga / bizga kvartira yoqadi."},
                      {original:"Ich lebe/Wir leben gerne hier.",translate:"Men bu yerda alo darajada yashayapman."},
                      {original:"Unsere/Meine Nachbarn sind sehr nett.",translate:"Bozning / mening qo`shnilarim juda yoqimli."},
                      {original:"Es gibt viele Probleme mit dem Nachbarn/der Nachbarin/den Nachbarn.",translate:"Qo`shnilar bilan juda muammolar bor."},
                      {original:"Ich will/möchte nicht mehr allein leben.",translate:"Men yolg`iz yashamoqchimasman."},
                      {original:"Die Wohnung ist sehr gemütlich/ungemütlich.",translate:"Kvartira juda shinam / shinam emas."},
                      {original:"Ich finde die Wohnung zu klein.",translate:"Men juda kichkina kvartira topayapman."},
                      {original:"Ich finde, die Wohnung ist zu klein.",translate:"Men juda kichkina kvartira topayapman."},
                      {original:"Die Wohnung ist groß (genug).",translate:"Kvartira katta."},
                      {original:"Unsere Wohnung ist 60 Quadratmeter (m²) groß.",translate:"Bizning kvartira 60 m 2."},
                      {original:"Sie ist perfekt/ideal/zu klein für uns.",translate:"U qulay / o`ylaganimdek / juda kichkina biz uchun."},
                      {original:"Leider gibt es keinen Aufzug und wir müssen die Treppe benutzen.",translate:"Afsuski lift yo`q va miz etajdan foydalanishimiz kerak."},
                      {original:"Ich wohne/Wir wohnen zur Miete.",translate:"Men yashayapman ijarada."},
                      {original:"Die Miete ist 650 Euro.",translate:"Ijara 650 euro."},
                      {original:"Wir zahlen 580 Euro Miete plus/inklusive Nebenkosten.",translate:"Biz 590 euro (qo`shimcha harajatlari bilan.) to`laymiz."},
                      {original:"Die Wohnung/Das Haus gehört mir/uns.",translate:"Kvartira / uy menga / bizga tegishli."},
                      {original:"Wir haben die Wohnung/das Haus vor einem Jahr/vier Jahren gekauft.",translate:"Biz kvartirani / uyni bir yil oldin / to`rt yil oldin sotib olganmiz."},
                      {original:"Wir brauchen eine große Wohnung. Deshalb wollen wir umziehen.",translate:"Bizga kattakon kvartira kerak. Shu sababli biz ko`chmoqchimiz."},
                      {original:"Im Juli muss ich ausziehen.",translate:"Iyulda men kvartiradan chiqishim kerak."},
                      {original:"Ich suche eine Wohnung. Die Wohnung muss zwei Schlafzimmer, eine Küche und ein Bad haben.",translate:"Men kvartira izlayapman. Kvartirada ikkita uhlash xonasi , oshxona va hammomi bo`lishi kerak."},
                      {original:"Ich habe ein Auto. Deshalb brauche ich (auch) eine Garage.",translate:"Menda mashina bor. Shu sababdan menga garaj kerak."},
                      {original:"Ich brauche keine Garage, weil ich kein Auto habe.",translate:"Menga garaj kerak emas, chunki mening mashinam yo`q."},
                      {original:"Wir möchten ein Haus kaufen.",translate:"Men uy sotib olmochiman."},
                      {original:"Wir suchen schon lange ein neues Haus.",translate:"Men allaqachondan beri yangi uy-joy qidirayapman."},
                      {original:"Ich suche eine Wohnung im Stadtzentrum/am Stadtrand.",translate:"Men shahar markazida / shahar chetida kvartira qidirayapman."},
                      {original:"Ich habe eine billige/schöne/große/möblierte Wohnung gefunden.",translate:"Men arzon / chiroyli / katta / jihozlangan kvartira topgandim."},
                      {original:"Wir können am ersten Juni einziehen.",translate:"Biz 1-iyunda ko`chib kira olamiz."},
                      {original:"Nächsten Monat ziehe ich ein.",translate:"Keyingi oy men ko`chib kirayapman."},
                      {original:"In einer Woche kann ich einziehen.",translate:"Bir hafta ichida men ko`chib kira olaman."},
                      {original:"In der Nähe von meiner Wohnung/meinem Haus ist eine Bushaltestelle, eine Straßenbahnhaltestelle und eine U-Bahn-Station.",translate:"Mening kvartiram yaqinida avtobus bekati , trolleybus bekati , metro stansiyasi bor."},
                      {original:"Ich bin (nicht) oft zu Hause.",translate:"Men tez-tez yangi uyda bo`laman."},
                      {original:"Ich arbeite zu Hause.",translate:"Men uyda ishlayapman."},
                      {original:"Ich arbeite von zu Hause aus.",translate:"Men uyda ishlayapman."},
                      {original:"Ich komme immer (erst) spät nach Hause.",translate:"Men uyga har doim kech kelayapman."},
                      {original:"Ich bekomme/Wir bekommen oft Besuch von Freunden.",translate:"Men tez-tez do`stimning tashrifini qabul qilayapman."},
                    ]
                  },

                  {
                    key: "8",
                    title: "Meine Wohnung / Mein Haus",
                    content:
                      "Meine Wohnung / Mein Haus - mening kvartiram / mening uyim",
                      stundeGaps: [
                        {original:"Wo wohnst/lebst du? Wo wohnt/lebt ihr? Wo wohnen/leben Sie?",translate:"Qayerda yashayapsan? Qayerda yashayapsizlar? Qayerda yashayapsiz?"},
                        {original:"Wohnst du/Wohnt ihr/Wohnen Sie in einem Dorf oder in einer Stadt?",translate:"Sen/ sizlar/ siz qishloqda yashayapsan(siz)mi yoki shaharda?"},
                        {original:"Wohnst du/Wohnt ihr/Wohnen Sie im Stadtzentrum oder am Stadtrand?",translate:"Sen/ sizlar/ siz shahar markazidami yo shahar chetida yashayapsan(siz)mi?"},
                        {original:"Wohnst du/Wohnt ihr/Wohnen Sie in einem Haus oder in einer Wohnung?",translate:"Sen/ sizlar/ siz kvartiradami yoki hovlida yashayapsan(siz)mi?"},
                        {original:"Wo ist das/dein/euer/Ihr Haus? Wo ist die/deine/eure/Ihre Wohnung?",translate:"Qayerda sening / sizlarning / sizning uying(ingiz)? Qayerda sening / sizlarning / sizning kvartirang(iz)?"},
                        {original:"Ist das Haus/die Wohnung im Stadtzentrum/am Stadtrand/in einem Dorf?",translate:"Uymi / kvartirami shahar markazidagi / shahar chetidagi / qishloqdagi?"},
                        {original:"Wohnst du (lieber) in der Stadt oder auf dem Land?",translate:"Sen shahardami yo qishloqda yashayapsanmi?"},
                        {original:"In welchem Stadtteil/Stadtviertel wohnst du/wohnt ihr/wohnen Sie?",translate:"Qaysi shahar kvartalida yashayapsan(siz)?"},
                        {original:"Wie ist der Stadtteil/das Stadtviertel?",translate:"Qanday mahalla?"},
                        {original:"Seit wann wohnst du dort?",translate:"Qachondan beri sen u yerda yashayapsan?"},
                        {original:"Wohnt ihr schon lange dort?",translate:"Sizlar qancha vaqt u yerda yashadingizlar?"},
                        {original:"Wohnen Sie schon immer dort?",translate:"Siz har doim u yerda yashayapsizmi?"},
                        {original:"Warum suchst du/sucht ihr/suchen Sie eine neue Wohnung/ein neues Haus?",translate:"Nima uchun kvartira qidirayapsan(siz)?"},
                        {original:"Wo hast du/habt ihr/haben Sie vorher gewohnt?",translate:"Qayerda yashagansan(siz)?"},
                        {original:"Wie ist die Wohnung/das Haus?",translate:"Qanday kvartira/ uy?"},
                        {original:"In welchem Stock ist die Wohnung?",translate:"Qaysi etajda kvartira?"},
                        {original:"In welcher Etage ist die Wohnung?",translate:"Qaysi etajda kvartira?"},
                        {original:"Wie groß ist die/deine/eure/Ihre Wohnung?",translate:"Qanchalik kvartirang(iz) katta?"},
                        {original:"Wie groß ist das/dein Zimmer/WG-Zimmer?",translate:"Qanchalik kvartira(yotoqxonadagi xona) katta?"},
                        {original:"Wie groß ist dein/euer/Ihr Haus?",translate:"Qanchalik katta uying(iz)?"},
                        {original:"Ist die Wohnung/das Haus groß genug?",translate:"Kvartirang yetarlicha darajada kattami?"},
                        {original:"Wie viele Zimmer hat die Wohnung?",translate:"Necha xonali kvartira?"},
                        {original:"Hat die Wohnung/das Haus ein Esszimmer/Gästezimmer/Arbeitszimmer/Wohnzimmer?",translate:"Kvartirada (uyda)  ovqatlanish xonasi / mehmonxona / ishxona / dam olish xona bormi?"},
                        {original:"Hast du eine Garage/eine Terrasse? Habt ihr einen Garten/einen Keller?",translate:"Senda garaj / ayvon bormi? Sizlarda bog` / podval bormi?"},
                        {original:"Haben Sie einen Balkon?",translate:"Sizda balkon bormi?"},
                        {original:"Gibt es eine Bushaltestelle, Straßenbahnhaltestelle oder U-Bahn-Station in der Nähe?",translate:"Yaqinda bekat bormi / ... ?"},
                        {original:"Was ist/Was gibt es in der Nähe von der/deiner/eurer/Ihrer Wohnung?",translate:"Uying(iz) yaqinida nima bor?"},
                        {original:"Wohnst du allein? Wohnt ihr mit Freunden zusammen?",translate:"Sen yolg`iz yashayapsanmi? Sizlar do`stlaringiz bilan yashayapsizlarmi?"},
                        {original:"Wohnen Sie mit Ihrer Familie zusammen?",translate:"Siz oilangiz bilan birga yashayapsizmi?"},
                        {original:"Mit wem wohnst du/wohnt ihr/wohnen Sie zusammen?",translate:"Kim bilan birga yashayapsan(siz)?"},
                        {original:"Seit wann lebt ihr/leben Sie zusammen?",translate:"Qachondan beri birga yashayapsizlar?"},
                        {original:"Wohnst du noch bei deinen Eltern? Wohnt ihr noch bei euren Eltern?",translate:"Sen hali ham ota-onangnikida yashayapsanmi? Sizlar hali ham ota-onangiznikida yashayapsizlarmi?"},
                        {original:"Wann hast du/habt ihr/haben Sie die Wohnung/das Haus gekauft?",translate:"Qachon kvartirani(uyni) sotib olding(iz)?"},
                        {original:"Wohnst du zur Miete? Wohnt ihr zur Miete? Wohnen Sie zur Miete?",translate:"Sen ijaraga yashaysanmi? Sizlar ijarada yashayapsizlarmi?"},
                        {original:"Wie hoch ist die Miete?",translate:"Ijara qancha turadi?"},
                        {original:"Wie viel Miete zahlst du/zahlt ihr?",translate:"Ijaraga qancha to`layapsan(siz)?"},
                        {original:"Wie teuer ist die Wohnung?",translate:"Qanchalik qimmat kvartirang?"},
                        {original:"Gefällt dir deine Wohnung? Gefällt euch eure Wohnung?",translate:"Senga(sizga) o`zingning(o`zingizning) kvartirangiz yoqadima?"},
                        {original:"Gefällt Ihnen Ihre Wohnung?",translate:"Sizga kvartirangiz yoqadima?"},
                        {original:"Wohnst du gern dort? Wohnt ihr gern dort? Wohnen Sie gern dort?",translate:"Sen(siz,sizlar) maza qilib qayerda yashayapsan(siz)?"},
                      ]
                    },

                    {
                      key: "9",
                      title: "Arbeit",
                      content:
                        "Arbeit - ish!",
                        stundeGaps: [
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                          {original:"",translate:""},
                        ]
                      },

                      {
                        key: "10",
                        title: "Arbeit",
                        content:
                          "Arbeit - ish!",
                          stundeGaps: [
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                            {original:"",translate:""},
                          ]
                        },

        //                 {
        //                   key: "11",
        //                   title: "Arbeit",
        //                   content:
        //                     "Arbeit - ish!",
        //                     stundeGaps: [
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                     ]
        //                   },

        //                   {
        //                     key: "12",
        //                     title: "Arbeit",
        //                     content:
        //                       "Arbeit - ish!",
        //                       stundeGaps: [
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                       ]
        //                     }
      ],
}
  
  
  
  export const germanStundeReducer = (state = initialState, action) => {
    switch (action.type) {
      
        default: return state
    }
  };
  