const initialState = {
    stunde: [
        {
          key: "1",
          title: "Arbeit",
          content:
            "Arbeit - Ish",
            stundeGaps: [
              {original:"Ich arbeite seit vier Jahren als Grafiker bei der Firma XZ-Media.",translate:"Men 4 yildan beri grafikchi bo`lib XZ-Media firmasida ishlayapman!"},
              {original:"Ich arbeite schon sieben Jahre als Kfz-Mechaniker in einer Autowerkstatt.",translate:"Men allaqachon 7yildan beri Kfz-mexanigi bo`lib mashina zavodida ishlayman!"},
              {original:"Von August 2013 bis Juli 2015 habe ich als Lehrer gearbeitet. ",translate:"2013-yil avgustidan 2015-yil iyuligacha o`qtuvchi bo`lib ishlaganman."},
              {original:"Meine Arbeitszeit ist/geht täglich von 8:00 Uhr bis 16:30 Uhr.",translate:"Mening ish vaqtim kunduzi soat 8:00 dan 16:30 gacha davom etadi!"},
              {original:"Um 13 Uhr haben/machen wir eine halbe Stunde Mittagspause.",translate:"Soat 13:00 da biz bir yarim soat tushki pauzada bo`lamiz!"},
              {original:"Ich esse mit meinen Arbeitskollegen zu Mittag.",translate:"Men birga ishlayotganlarim bilan tushlikni yeyapman."},
              {original:"Ich arbeite acht Stunden pro Tag/40 Stunden pro Woche.",translate:"Men kuniga 8 soat,haftasiga esa 40 soat ishlayman."},
              {original:"Um vier Uhr nachmittags bin ich mit meiner Arbeit fertig. Dann gehe ich nach Hause. Um 17 Uhr habe ich Feierabend. Nach der Arbeit gehe ich oft einkaufen. ",translate:"- Men 16:00 da ish bilan band bo`laman.Keyin esa uyga boraman.Menda soat 17:00da kechki bayram bo`ladi.Ishdan keyin tez harid qilish uchun boraman."},
              {original:"Zweimal pro Woche gehe ich nach der Arbeit ins Fitnessstudio/Fitnesscenter.",translate:"Haftasiga ikki marta ishdan keyin Fittnes klubga boraman."},
              {original:"Nach der Arbeit gehe ich zum/in den Sprachkurs.",translate:"Men ishdan keyin til kursiga boraman."},
              {original:"Ich arbeite in der Stadt, aber ich lebe in einem Dorf in der Nähe. Deshalb brauche ich ein Auto. ",translate:"Men shaharda ishlayman, lekin yaqindag qishloqda yashayman. Shu sababli menga mashina kerak."},
              {original:"Ich muss jeden Tag Tag 15 Kilometer mit dem Bus/dem Zug/dem Auto/der S-Bahn zur Arbeit fahren.",translate:"- Men har kuni 15 kilometrni avtobusda/poezda/mashinada/metroda ishga borishim kerak."},
              {original:"Ich fahre mit dem Fahrrad/dem Motorrad/der Straßenbahn/der U-Bahn zur Arbeit.",translate:"Men velosiped bilan/mototsikl bilan/metro bilan/tramvay bilan ishga borayapman"},
              {original:"Ich habe es nicht weit zur Arbeit.",translate:"Mening ish joyim uzoq emas."},
              {original:"Ich wohne in der Nähe von meiner Arbeit. Deshalb kann ich zu Fuß zur Arbeit/dorthin gehen.",translate:"Men o`zimning ish joyimdan uzoq bo`lmagan joyda yashayman.Shu sababli men ishga/u yoqqa piyoda bora olaman"},
              {original:"Ich gehe/fahre/brauche (nur) eine halbe Stunde zur Arbeit.",translate:"Men yarim soatda ishga borayapman."},
              {original:"Meine Arbeit/Mein Job gefällt mir (nicht).",translate:"Mening ishim menga yoqadi(yoqmaydi)."},
              {original:"Ich mag meine Arbeit/meinen Job (nicht).",translate:"Menga o`zimni ishim yoqadi(yoqmaydi)."},
              {original:"Meine Arbeit/Mein Job ist sehr stressig und ich habe (leider) nicht viel Freizeit.",translate:"Mening ishim juda strogiy va menda (afsuski) bo`sh vaqtim ko`p emas."},
              {original:"Ich habe eine interessante/stressige Arbeit.",translate:"Menda qiziqarli/strogiy ishim bor."},
              {original:"Ich verdiene wenig/zu wenig/schlecht/genug/gut/viel.",translate:"Men kam/juda kam/yomon/yaxshi/yetarli/ko`p pul ishlab topaman."},
              {original:"Ich verdiene ungefähr 1.300 Euro netto.",translate:"Men taxminan 1.300 Euro pul ishlab topaman."},
              {original:"Jetzt bin ich Rentner/Rentnerin, aber früher habe ich als Fotograf/Fotografin gearbeitet.",translate:"Men hozir nafaqaho`rman,lekin avval rasmchi bo`lib ishlaganman."},
              {original:"Ich bin schon sieben Monate arbeitslos.",translate:"Men allaqachon 7oydan beri ishsizman."},
              {original:"Ich bin seit einem Jahr/seit drei Jahren/seit dem Sommer/seit Januar 2016 arbeitslos. ",translate:"Men bir yildan beri/uch yildan beri/yozdan beri/2016-yil yanvardan beri ishsizman."},
              {original:"Ich habe keine Arbeit/keinen Job.",translate:"Meni ishim yo`q."},
              {original:"Ich suche seit einem halben Jahr (eine) Arbeit/einen Job.",translate:"Men yarim yildan beri ish qidirayapman."},
              {original:"Seit einem Monat suche ich eine Arbeitsstelle.",translate:"Men bir oydan beri ish joy qidiryapman."},
              {original:"Vor vier Monaten habe ich einen neuen Job/eine neue Arbeitsstelle gefunden.",translate:"Men 4oy oldin yangi ish joyini topdim."},
              {original:"Ich lerne Deutsch, weil ich es für meine Arbeit brauche.",translate:"Men nemis tilini o`rganayapman,chunki mening ishim uchun kerak bo`layapdi."},
              {original:"Ich möchte in Deutschland/in Österreich/in der Schweiz arbeiten, deshalb lerne ich Deutsch.",translate:"Men Germaniyada/Avstriyada/Shwetsiyada ishlamoqchiman,shu sababli nemis tilini o`rganayapman."},
              {original:"Auf der Arbeit trage ich andere Kleidung/Klamotten als in meiner Freizeit.",translate:"Ishda men boshqa kiyimlarni bo`sh vaqtimda kiyib ko`raman."},
              {original:"Auf der Arbeit trage ich elegante Kleidung/eine Uniform.",translate:"Men ishda chiroyli kiyimni/uniformani kiyaman."},
              {original:"Für die Arbeit muss ich mich elegant kleiden/anziehen.",translate:"Men ishga yaxshi kiyinishim kerak."},
              {original:"Bei der Arbeit trage ich Anzug, Hemd und Krawatte.",translate:"Ishda kostyum,ko`ylak va galstukda bo`laman."},
              {original:"Beim Arbeiten trage ich ein Kleid oder einen Hosenanzug und eine Bluse.",translate:"Ishda ko`ylakda yoki kofta yupkada bo`laman."},
              {original:"Ich bin krank/krankgeschrieben. Deshalb kann ich nicht auf die Arbeit gehen/arbeiten gehen.",translate:"Men kasalman.Shu sabali ishga bora olmayapman."},
              {original:"Nächste Woche kann ich wieder arbeiten gehen.",translate:"Keyingi hafta men yana ishlay olaman."},
                ],
        },
        {
          key: "2",
          title: "Arbeit",
          content:
            "Arbeit - ish!",
            stundeGaps: [
              {original:"Arbeitest du? Arbeitet ihr? Arbeiten Sie?",translate:"Sen ishlaysanmi? Sizlar ishlaysizlarmi? Siz ishlaysizmi?"},
              {original:"Arbeitest oder studierst du? Arbeitet oder studiert ihr? Arbeiten oder studieren Sie?",translate:"Ishlaysanmi yoki o`qiysanmi? Ishlaysizlarmi yoki o`qiysizlarmi? Ishlaysizmi yo o`qiysizmi?"},
              {original:"Arbeitest du oder gehst du noch zur Schule?",translate:"Ishlaysanmi yoki hali ham maktabga borasanmi?"},
              {original:"Arbeiten Sie oder machen Sie eine Ausbildung?",translate:"Ishlaysizmi yoki ausbildung (o`qiysizmi?) qilasizmi?"},
              {original:"Wo arbeitest du/arbeitet ihr/arbeiten Sie?",translate:"Qayerda ishlaysan / ishlaysizlar / ishlaysiz?"},
              {original:"Seit wann arbeitest du in München? Seit wann arbeiten Sie bei dieser Firma?",translate:"Qachondan  beri Muyunxenda ishlaysan? Qachondan beri bu firmada ishlaysiz?"},
              {original:"Seit wann arbeitest du als Kellner?",translate:"Qachondan beri ofitsant bo`lib ishlaysan?"},
              {original:"Wie sind deine/eure/Ihre Arbeitszeiten?",translate:"Qanday sening / sizlarning / sizning ish vaqtingiz?"},
              {original:"Wann fängt deine/eure/Ihre Arbeit an?",translate:"Qachon sening / sizlarning / sizning ishlaringiz boshlanadi?"},
              {original:"Wann beendest du deine Arbeit? Wann beenden Sie Ihre Arbeit?",translate:"Qachon ishingni tugatasan? Qachon ishingizni tugatasiz?"},
              {original:"Wann bist du/seid ihr/sind Sie mit der Arbeit/mit Arbeiten fertig?",translate:"Qachon (sen) siz ish bilan band bo`lasiz?"},
              {original:"Wann hast du/habt ihr/haben Sie Feierabend?",translate:"Qachon senda / sizlarda / sizda kechki bayram bor?"},
              {original:"Wie viele Stunden arbeitest du/arbeiten Sie pro Tag/Woche?",translate:"Necha soat kuniga ishlayapsiz (ishlayapsan)?"},
              {original:"Was machst du/macht ihr/machen Sie nach der Arbeit?",translate:"Ishdan keyin nima qilayapsan (qilayapsizlar ,qilayapsiz)?"},
              {original:"Hast du viel/genug Freizeit?",translate:"Senda ko`p / yetarlicha bo`sh vaqt bormi?"},
              {original:"Hast du es weit (bis) zur Arbeit?",translate:"Senga ishgacha uzoqmi?"},
              {original:"Wie kommst du/kommt ihr/kommen Sie zur Arbeit?",translate:"Ishga qanday borayapsan (borayapsizlar , borayapsiz)?"},
              {original:"Kannst du/Könnt ihr/Können Sie zu Fuß zur Arbeit gehen?",translate:"Sen (sizlar ,siz) ishga piyoda bora olasanmi (olasizlarmi , olasizmi)?"},
              {original:"Fährst du/Fahrt ihr/Fahren Sie mit dem Auto zur Arbeit?",translate:"Sen (sizlar ,siz) ishga mashina bilan borasanmi (borasizlarmi ,borasizmi)?"},
              {original:"Wie lange fährst du/brauchst du (bis) zur Arbeit?",translate:"Qanchalik uzoq ish joyigacha?"},
              {original:"Wie findest du deine Arbeit/deinen Job? Wie findet ihr eure Arbeit/euren Job?",translate:"Ish joyini qanday topding (topdingiz)?"},
              {original:"Gefällt dir deine Arbeit/dein Job?",translate:"Senga ish joying yoqadima?"},
              {original:"Gefällt euch eure Arbeit/euer Job?",translate:"Sizlarga ish joylaringiz yoqadima?"},
              {original:"Gefällt Ihnen Ihre Arbeit/Ihr Job?",translate:"Sizga ish joyingiz yoqadima?"},
              {original:"Verdienst du/Verdient ihr genug? Verdienen Sie gut?",translate:"Sen (siz) yetarlicha pul ishlaysanmi (ishlaysizlarmi)?"},
              {original:"Wie viel (Geld) verdienst du?",translate:"Qancha pul topasan?"},
              {original:"Seit wann bist du/seid ihr/sind Sie (schon) arbeitslos?",translate:" - Qachondan beri ishsizsan (ishsizsizlar , ishsizsiz)?"},
              {original:"Warum suchst du/sucht ihr/suchen Sie eine neue Arbeit?",translate:"Nima uchun sen (sizlar , siz) yangi ish joyini qidirayapsan (qidirayapsizlar , qidirayapsiz)?"},
              {original:"Seit wann suchst du/sucht ihr/suchen Sie schon einen (neuen) Job/eine Arbeitsstelle?",translate:"Qachondan beri ish joyini qidirayapsan (qidirayapsizlar , qidirayapsiz)?"},
              {original:"Welche Kleidung trägst du/tragt ihr/tragen Sie auf der Arbeit?",translate:"Ishda qanaqa kiyimlarni kiyinasan (kiyinasizlar , kiyinasiz)?"},
              {original:"Was für Klamotten trägst du auf der Arbeit?",translate:"Ishda qanaqa kiyimda bo`lasan?"},
                ],
        },
        

        {
          key: "3",
          title: "Wohnort",
          content:
            "Wo ich wohne und wo ich gewohnt habe.",
            stundeGaps: [
              {original:"Ich lebe/wohne in Berlin/in Deutschland.",translate:"Men Berlinda  / Germaniyada yashayapman."},
              {original:"Ich lebe/wohne in der Türkei/in der Schweiz.",translate:"Men Turkiyada / Shwetsiyada yashayapman."},
              {original:"Ich lebe/wohne im/in Iran.",translate:"Men Iroqda yashayapman."},
              {original:"Ich lebe/wohne in den USA/in den Niederlanden.",translate:"Men Amerikada / Niderlandiyada yashayapman."},
              {original:"Ich lebe/wohne auf Teneriffa/auf Mallorca/auf Korsika/auf einer Insel.",translate:"Men orolda(...) yashayapman."},
              {original:"Ich komme aus Usbekistan, aber ich lebe seit 2015 in Deutschland.",translate:"Men Usbekistandan kelganman, lekin 2015 yildan beri Germaniyada yashayapman."},
              {original:"Ich lebe in einer Stadt/in einem Dorf/auf dem Land.",translate:"Men shaharda / qishloqda yashayapman."},
              {original:"Berlin liegt im Osten von Deutschland.",translate:"Germaniyaning sharqida Berlin joylashgan."},
              {original:"Die Stadt liegt im Norden/im Süden/im Westen/im Osten/im Zentrum von Usbekistan.",translate:"Shahar O`zbekistonning shimolida / Janubida / G`arbida / Sharqida / markazida joylashgan."},
              {original:"Das Dorf liegt in der Nähe von Hamburg.",translate:"Qishloq Hamburgdan uzoq bo`lmagan joyda joylashgan."},
              {original:"Erpel liegt bei Bonn.",translate:"Erpel Bonnda joylashgan."},
              {original:"Mein Dorf liegt/ist etwa 20 Kilometer von Wien entfernt.",translate:"Mening qishlog`im Vena shahridan 20 kilometrlar chamasidagi uzoqlikda joylashgan."},
              {original:"Die Stadt/Das Dorf liegt an einem Fluss.",translate:"Shahar / qishloq daryo bo`yida joylashgan."},
              {original:"Der Ort liegt am Rhein. Die Stadt liegt an der Elbe.",translate:"Bu joy Rayn daryosi bo`yida joylashgan. Shahar Elba daryosi bo`yida joylashgan!"},
              {original:"Ich wohne/lebe schon immer in Berlin. Ich bin hier geboren und aufgewachsen.",translate:"Men har doim Germaniyada yashayman. Men bu yerda tug`ilganman va katta bo`ldim."},
              {original:"Ich wohne/lebe seit dreizehn Jahren im Zentrum/in der Altstadt/am Stadtrand von Zürich.",translate:"Men 13 yildan beri Zurix shahrining markazida / eski shahrida / shahar chetida yashayapman."},
              {original:"Ich lebe seit 2003 mit meinem Freund/meinem Mann in Hamburg.",translate:"Men 2003-yildan beri do`stim bilan / erim bilan Hamburgda yashayapman."},
              {original:"Ich wohne schon lange mit meiner Freundin/meiner Frau/meiner Familie in Dresden.",translate:"Men anchadan beri dugonam bilan / hotinim bilan / oilam bilan Dresdenda yashayapman."},
              {original:"Ich lebe seit zehn Jahren mit meinem Kind in Weimar.",translate:"Men o`n yildan beri farzandim bilan Vaymerda yashayapman."},
              {original:"Ich wohne seit einem Jahr mit meinen Kindern in Leverkusen.",translate:"Men 1 yildan beri farzandim bilan Leverkusenda yashayapman."},
              {original:"Vor drei Jahren bin ich von Bonn nach Berlin gezogen.",translate:"3 yil oldin Bondan Berlinga ko`chib kelgandim."},
              {original:"Mit 16 Jahren bin ich nach Deutschland gekommen/gegangen.",translate:"16 yoshimda Germaniyaga kelganman."},
              {original:"Früher/Vorher habe ich in Madrid/in Marokko/in der Türkei gelebt.",translate:"Avval Madridda / Marokkoda / Turkiyada yashadim."},
              {original:"Vor 5 Jahren bin ich/ist meine Familie von Nürnberg nach München gezogen.",translate:"5 yil oldin mening oilam Nurnbergdan Munxenga ko`chib kelishgan."},
              {original:"Von 2008 bis 2013 habe ich in Konstanz gelebt.",translate:"2018-yildan 2013-yilgacha Konstanda yashagandim."},
              {original:"Ich habe lange (Zeit) in Süddeutschland gelebt.",translate:"Men uzoq vaqt Janubiy Germaniyada yashadim."},
              {original:"Ich lebe/wohne bei meinem Vater/meiner Mutter/meinen Eltern.",translate:"Men otamnikida / onamnikida / ota-onamnikida yashayapman."},
              {original:"Unsere Kinder wohnen/leben nicht mehr bei uns. Sie sind vor ein paar Jahren ausgezogen.",translate:"Bizning farzandlar biznikida yashashmaydilar. Ular ikki yil oldin ko`chib ketishgan!"},
              {original:"Ich wohne/lebe in einer Wohngemeinschaft/WG.",translate:"Men yotoqxonada yashayapman."},
              {original:"Ich wohne mit meiner Familie in einem Haus am Stadtrand.",translate:"Men oilam bilan shahar chetida yashaymiz."},
              {original:"Ich wohne in einer Wohnung im Stadtzentrum.",translate:"Men bir honalik kvartirada shahar markazida yashayman!"},
              {original:"Wir haben eine kleine Wohnung im Zentrum.",translate:"Biz shahar markazida kichkina uyda yashaymiz!"},
              {original:"Mein Stadtteil/Stadtviertel heißt…",translate:"Mening mahallam ataladi ..."},
              {original:"Die Stadt/Das Dorf ist klein/groß/nicht sehr groß.",translate:"Shahar / Qishloq kichkina / katta / katta emas."},
              {original:"Die Stadt hat ungefähr/fast/über eine Million/zwei Millionen Einwohner.",translate:"Shahar taxminan / deyarli / 1 milliondan ortiq / 2 milliondan ortiq aholi bor."},
              {original:"In Freiburg leben etwa 230.000 Menschen/Personen.",translate:"Frayburgda Taxminan 230 000 inson yashaydi."},
              {original:"Die Stadt/Das Dorf ist (schon) sehr alt.",translate:"Shahar / qishloq juda qadimiy."},
              {original:"Ich wohne/lebe (nicht) gern in…",translate:"Men maza qilib yashaya(ma)pman ...da."},
              {original:"Ich lebe (nicht) gern in diesem Stadtteil.",translate:"Men maza qilib bu shahar qismida yashaya(ma)pman."},
              {original:"Die Stadt/Der Stadtteil gefällt mir (nicht).",translate:"Bu shahar/ mahalla menga yoqadi (yoqmaydi)."},
              {original:"Meine Freunde und Familie leben (auch) hier.",translate:"Mening do`stim va oilam bu yerda yashaydi."},
              {original:"Ich habe (nicht) gern in… gelebt.",translate:"Men maza qilib qaysidir shaharda yashay ol(ma)dim."},
              {original:"Ich mag den Stadtteil/die Stadt/das Dorf/die Region.",translate:"Menga mahalla / shahar / qishloq / region yoqadi."},
              {original:"Ich lebe noch nicht so lange/erst drei Monate hier und kenne noch nicht so viele Leute.",translate:"Men unchalik uzoq emas / endi 3 oy bo`ldi yashayotganimga va men hali hamma odamlarni tanimayman."},
              {original:"Ich lebe in…, aber arbeite in… ",translate:"Men qaysidir shaharda yashayman , lekin boshqa qaysidir shaharda ishlayapman."},
              {original:"Deshalb muss ich mit dem Auto/mit dem Bus/mit dem Zug zur Arbeit fahren.",translate:"Shu sababli mashina bilan / avtobus bilan / poyezd bilan ishga bormoqchiman."},
              {original:"Ich möchte/will hier nicht (mehr) leben.",translate:"Men bu yerda ishlamoqchi(mas)man."},
              {original:"Ich möchte/will (für) immer hier leben.",translate:"Men bu yerda yashamoqchiman."},
              {original:"Ich möchte/will in… leben. ",translate:"Men qaysidir shaharda yashamoqchiman."},
              {original:"Ich habe ein Jahr (lang) in Paris gelebt.",translate:"Men parijda 1 yil yashaganman."},
              {original:"Salzburg gefällt mir, weil man dort viel machen kann.",translate:"Salzburg menga yoqadi , chunki u yerda ko`p narsa qila olaman."},
              {original:"Paris ist meine Lieblingsstadt.",translate:"Parij mening sevimli shaharim."},
              {original:"Meine Lieblingsstadt ist Berlin.",translate:"Mening sevimli sharim Berlin."},
              {original:"Ich wohne gern in der/dieser Stadt.",translate:"Men bajonidil bu shaharda yashayapman."},
              {original:"Ich lebe lieber auf dem Land als in der Stadt.",translate:"Men bajonidil shahar sifatidagi qishloqda yashayapman."},
            ]
          },

          {
            key: "4",
            title: "Wohnort",
            content:
              "Was es an meinem Wohnort gibt?",
              stundeGaps: [
                {original:"In… gibt es viele Hotels, Geschäfte, Supermärkte und ein großes Einkaufszentrum.",translate:"Qaysi shahardadir juda ko`p mehmonhonalar / magazinlar / supermarktlar va savdo majmualari bor."},
                {original:"Ich wohne im Zentrum, deshalb gibt es viele Geschäfte in der Nähe.",translate:"Men markazda yashayapman , chunki yaqin orada ko`p magazinlar bor."},
                {original:"In dem Stadtteil gibt es viele Kneipen, Cafés und Restaurants. Es gibt auch ein Kino, einen Park und ein Museum.",translate:"- Bu shaharning qismida ko`plab Kafelar , restaranlar va barlar.Bu yerda kino , park va muzey bor."},
                {original:"Alles ist in der Nähe und ich kann immer zu Fuß gehen.",translate:"Hammasi yaqinda va men har doim piyoda bora olmayman."},
                {original:"Deshalb wohne ich gern im Zentrum.",translate:"Shu sabali men shahar markazida yashayapman."},
                {original:"Leider gibt es in meinem Dorf keinen Supermarkt. Deshalb brauche ich ein Auto. ",translate:"Afsuski mening qishlog`imda Supermarkt yuq.Shu sababli menga mashina kerak."},
                {original:"In… haben wir eine Bäckerei, eine Metzgerei und ein kleines Lebensmittelgeschäft. ",translate:"Qaysidir joyda bizda qassobhona va kichkina savdo magazini."},
                {original:"Außerdem gibt es einen Arzt und eine Apotheke.",translate:"Bundan tashqari 1 ta shifohona va apteka ham bor."},
                {original:"Es gibt (leider) keine Apotheke. Es fehlt eine Apotheke.",translate:"Afsuski u yerda apteka yuq. Dorixona yo'q."},
                {original:"In… gibt es viele Kindergärten und Schulen. Es gibt auch ein Krankenhaus.",translate:"Qaysidir joyda ko`plab bolalar bog`chasi va maktablar bor. Kasalhona ham bor."},
                {original:"Es gibt einen Kindergarten/eine Schule/eine Universität.",translate:"Bolalar bog`chasi , maktab , Universitet bor."},
                {original:"In der Altstadt sieht man viele alte Gebäude, Plätze und Kirchen.",translate:"Eski shaharda ko`plab eskiy binolar , maydonlar va madrasalarni ko`rishyapdilar."},
                {original:"Es gibt auch eine Moschee/eine Synagoge/einen Tempel.",translate:"Bu yerda ham bor masjidlar , ibodatxonalar."},
                {original:"Es gibt viele Hochhäuser.",translate:"Ko`plab osmono`par binolar bor."},
                {original:"Hier kann man sehr viele Sehenswürdigkeiten wie das alte Rathaus und die Kathedrale besichtigen.",translate:"Bu yerda juda ko`plab diqqatga sazovor joylar huddi eski oqsaroylarni kurishadilar."},
                {original:"Es gibt eine Straßenbahn, viele Busse und auch eine U-Bahn. Deshalb brauche ich kein Auto.",translate:""},
                {original:"Der Bahnhof ist im Zentrum von der Stadt.",translate:"Vokzal shahar markazida joylashgan."},
                {original:"Die Stadt hat einen Flughafen.",translate:"Shaharda aeroport bor."},
                {original:"Bonn ist die perfekte Stadt für mich.",translate:"Bon men uchun alo darajadagi shahar."},
                {original:"Für mich ist Freiburg die perfekte Stadt.",translate:"Menga Frayburg alo darajadagi shahar."},
                {original:"Was man an meinem Wohnort machen kann. ",translate:"Mening tug`ilgan joyimda nima qilsa bo`ladi?"},
                {original:"In meiner Stadt/meinem Dorf kann man sehr viel/nicht viel machen. ",translate:"Mening shaharimda / qishlog`imda juda ko`plab narsa qilsa bo`ladi (bo`lmaydi)."},
                {original:"Im Stadtzentrum gibt es viele Geschäfte. Dort kann man gut einkaufen gehen. Ich gehe dort oft mit meinen Freunden/meinen Freundinnen einkaufen/shoppen.",translate:"Shahar markazida ko`plab magazinlar bor.U yerga yaxshi savdo qilishga borsa bo`ladi.Men tez-tez u yoqqa boraman do`stlarim bilan."},
                {original:"Ich gehe dort oft mit meinen Freunden/meinen Freundinnen einkaufen/shoppen.",translate:"- Shahar markazida ko`plab magazinlar bor.U yerga yaxshi savdo qilishga borsa bo`ladi.Men tez-tez u yoqqa boraman do`stlarim bilan."},
                {original:"Ich fahre oft ins Stadtzentrum und gehe dort spazieren.",translate:"Men tez-tez shahar markaziga borayapman va u yerga sayohat qilishga boraman."},
                {original:"Auf dem Marktplatz gibt es dreimal pro Woche einen Markt. Dort kann man immer frische Produkte kaufen.",translate:"Bozor maydonida haftasiga 3 marta bozor bo`lib o`tadi.U yerda yangi mahsulotlarni sotib olishadilar."},
                {original:"Auf dem Markt kaufe ich oft frisches Obst und Gemüse.",translate:"Bozorda men tez-tez yangi sabzavotlarni va mevalarni sotib olayapman."},
                {original:"Das Freizeitangebot ist (sehr) groß und gut.",translate:"Dam olish taklifi juda yaxshi va katta."},
                {original:"Man kann Sport treiben, mit Freunden ins Kino oder (ins) Theater gehen und mit der Familie im Park spazieren gehen.",translate:"Sport bilan shug`urlanish , do`stlar bilan kinoga yoki teatrga borish va oila bilan parkda sayohat qilish mumkun."},
                {original:"Ich gehe oft in den Park, um dort mit Freunden Volleyball oder Fußball zu spielen. ",translate:"Men tez-tez parkka boraman , u yerda futbol yoki valeybol o`ynash uchun."},
                {original:"Es gibt viele Spielplätze. Dort können die Kinder spielen.",translate:"Ko`plab o`yin maydonlari bor. U yerda bolalar o`ynay oladilar."},
                {original:"Außerdem gibt es ein Schwimmbad. Im Sommer gehe ich mit meinen Freunden/meinen Freundinnen ins Schwimmbad.",translate:"Bundan tashqari suzish havzasi bor. Yozda men do`stlarim bilan suzish havzasiga boraman."},
                {original:"Die Stadt liegt am Meer und es gibt einen Strand. Ich gehe oft an den Strand.",translate:""},
                {original:"Ich mache gern Sport und trainiere dreimal pro Woche im Fitnessstudio.",translate:""},
                {original:"Es gibt oft gute Konzerte.",translate:"Tez-tez yaxshi konsertlar bo`ladi."},
                {original:"Im Museum gibt es oft interessante Ausstellungen.",translate:"Muzeyda tez-tez qiziqarli ko`rgazmalar bo`ladi."},
                {original:"Ich gehe oft ins Museum.",translate:"Men tez-tez muzeyga boraman."},
                {original:"In den Kneipen und Cafes kann man Freunde treffen.",translate:"Turli hil barlarda va kafelarda do`stlar uchrashisha olishadilar."},
                {original:"Man kann in… abends gut ausgehen / essen gehen.",translate:"Qaysidir joyda kechalarni yaxshi o`tkazsa bo`ladi."},
                {original:"Es gibt viele Restaurants. Dort kann man gut essen.",translate:"Ko`plab restaranlar bor. U yerda yaxshi ovqatlansa bo`ladi."},
                {original:"Ich wohne gern hier,…",translate:"Men bajonidil bu yerda yashayman , ..."},
                {original:"… weil die Stadt sehr interessant ist.",translate:"... chunki shahar juda chiroyli."},
                {original:"… weil man viel machen kann.",translate:"... chunki ko`p narsa qilsa bo`ladi."},
                {original:"… weil meine Familie hier lebt.",translate:"... chunki mening oilam bu yerda yashaydi."},
                {original:"… weil ich hier gute Freunde habe.",translate:"... chunki bu yerda yaxshi do`stlarim bor."},
                {original:"Ich lebe gern hier, denn die Stadt ist sehr ruhig und gemütlich.",translate:"Men bajonidil bu yerda yashayapman , chunki shahar tinch va juda qulay."},
                {original:"Ich finde die Stadt langweilig. Deshalb will ich nicht mehr hier leben.",translate:"Men shaharni zerikarli hisoblayman. Shu sababli men bu yerda ko`p yashamoqchimasman."},
              ]
            },

        //     {
        //       key: "5",
        //       title: "Arbeit",
        //       content:
        //         "Arbeit - ish!",
        //         stundeGaps: [
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //           {original:"",translate:""},
        //         ]
        //       },

        //       {
        //         key: "6",
        //         title: "Arbeit",
        //         content:
        //           "Arbeit - ish!",
        //           stundeGaps: [
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //             {original:"",translate:""},
        //           ]
        //         },

        //         {
        //           key: "7",
        //           title: "Arbeit",
        //           content:
        //             "Arbeit - ish!",
        //             stundeGaps: [
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //               {original:"",translate:""},
        //             ]
        //           },

        //           {
        //             key: "8",
        //             title: "Arbeit",
        //             content:
        //               "Arbeit - ish!",
        //               stundeGaps: [
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //                 {original:"",translate:""},
        //               ]
        //             },

        //             {
        //               key: "9",
        //               title: "Arbeit",
        //               content:
        //                 "Arbeit - ish!",
        //                 stundeGaps: [
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                   {original:"",translate:""},
        //                 ]
        //               },

        //               {
        //                 key: "10",
        //                 title: "Arbeit",
        //                 content:
        //                   "Arbeit - ish!",
        //                   stundeGaps: [
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                     {original:"",translate:""},
        //                   ]
        //                 },

        //                 {
        //                   key: "11",
        //                   title: "Arbeit",
        //                   content:
        //                     "Arbeit - ish!",
        //                     stundeGaps: [
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                       {original:"",translate:""},
        //                     ]
        //                   },

        //                   {
        //                     key: "12",
        //                     title: "Arbeit",
        //                     content:
        //                       "Arbeit - ish!",
        //                       stundeGaps: [
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                         {original:"",translate:""},
        //                       ]
        //                     }
      ],
}
  
  
  
  export const germanStundeReducer = (state = initialState, action) => {
    switch (action.type) {
      
        default: return state
    }
  };
  